### ISSUE TITLE
Segmentation Fault on successive press of History Key.

### ISSUE THREAD

**Issue by ragnarov** [CristianHenzel/ClipIt#168]
Heya,
Using clipit on arch linux (5.4.87-1-lts) amd64.
I have set my History Key to Ctrl+Alt+slash
Sometimes pressing the keys don't bring up the history menu.
If I press the keys on quick succession then Clipit crashes.

Crash is specific.
It is not important to use the keys quickly.
If history menu appears and I still press those above mentioned key,
then it crashes with 'Segmentation fault (core dumped)'.

I got this by starting clipit on a terminal.

Thanks for reading :)

**Comment by afelinczak** [comment]
I'm not sure if Arch package is up to date, we have that issue fixed for Debian and Ubuntu (compiled with GTK 3).
I see some comments regarding crash also in AUR version.
Safest option would be to try build from sources and let us know if it works.

**Comment by jgidi** [comment]
Just built sources with GTK3 version 3.24.24-2 on Arch, and still crashes. However, the crash happens when the pointer `match` inside `selected_by_input()` points to an empty char string. Then, it propagates to `underline_match()` and causes a segmentation fault on `gtk_label_set_attributes()`.
I have been testing it and will make a pull request soon.

**Comment by afelinczak** [comment]
Patch merged, ppa updated.
