### ISSUE TITLE
Prevent clipit from storing clipboard history

### ISSUE THREAD

**Issue by Phyks** [CristianHenzel/ClipIt#60]
Hi,

I am mainly using clipit to sync my primary and graphical clipboards, and I very rarely use the history feature. But there does not seem to be any way to prevent it from storing history, either temporarily or permanently.

Moreover, when using tools such as `pwgen` for generating passwords, the copied password is stored in clipit history, which can be a real security issue.

What about adding such a feature?

Thanks!

**Comment by CristianHenzel** [comment]
Hello,

did you try to set the history length to 1?
That would make ClipIt only store a single item in the history, basically the item that you have in your system clipboard too. If you don't regularly clear our your system clipboard, I don't really see this as a security issue, since the currently copied clipboard item can be seen by basically any application running on your system anyway.

**Comment by Phyks** [comment]
Indeed, but it seems that the minimum history length is 5. At least, it always goes back to 5 when I set 1. I am using clipit 1.4.3-1 from AUR.
